tests:
  Tetris-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Tetris
dependencies:
- random
- base >= 4.7 && < 5
- time
name: GameOfTetris
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Boaz Chen
github: boaz-chen/Tetris
executables:
  tetris:
    source-dirs: app
    main: Tetris.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Tetris
    dependencies:
    - containers
description: Please see the README on GitHub at <https://github.com/githubuser/Tetris#readme>
